xray_genius/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from ninja import NinjaAPI

from .core import views
from .core.rest.session import session_router

api = NinjaAPI(title='X-ray Genius', version='0.1.0')
api.add_router('/session/', session_router)

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('oauth/', include('oauth2_provider.urls')),
    path('admin/', admin.site.urls),
    path('hijack/', include('hijack.urls')),
    path('terms-of-service/', views.terms_of_service, name='terms-of-service'),
    path('guide/', views.guide, name='guide'),
    path('faq/', views.faq, name='faq'),
    path('api/v1/s3-upload/', include('s3_file_field.urls')),
    path('api/v1/', api.urls),
    path('captcha/', include('captcha.urls')),
    path('', views.dashboard, name='dashboard'),
    path('contact/', views.contact_form, name='contact'),
    path('contact/submitted/', views.contact_form_submitted, name='contact-submitted'),
    path('session/', views.upload_ct_input_file, name='create-session'),
    path(
        'session/from-sample-data/<int:sample_dataset_file_pk>/',
        views.start_session_with_sample_data,
        name='create-session-from-sample-data',
    ),
    path('session/<uuid:session_pk>/delete/', views.delete_session, name='delete-session'),
    path(
        'session/<uuid:session_pk>/input-ct-file/',
        views.download_ct_file,
        name='download-input-ct-file',
    ),
    path(
        'session/<uuid:session_pk>/viewer/',
        views.volview_viewer,
        name='viewer',
    ),
    path(
        'session/<uuid:session_pk>/initiate-batch-run/',
        views.initiate_batch_run,
        name='initiate-batch-run',
    ),
    path(
        'session/<uuid:session_pk>/cancel-batch-run/',
        views.cancel_batch_run,
        name='cancel-batch-run',
    ),
    path(
        'session/<uuid:session_pk>/trace/',
        views.get_task_trace,
        name='get-task-trace',
    ),
    # TODO: these are hardcoded because the frontend refers to them directly as absolute URLs
    path(
        'itk/<path:path>',
        RedirectView.as_view(url='/static/itk/%(path)s', permanent=True),
        name='itk',
    ),
]

if settings.DEBUG:
    import debug_toolbar
    import django_browser_reload.urls

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path('__reload__/', include(django_browser_reload.urls)),
        *urlpatterns,
    ]

xray_genius/core/models/contact_form.py
from django.db import models
from django_extensions.db.fields import CreationDateTimeField


class ContactFormSubmission(models.Model):
    created = CreationDateTimeField()

    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self) -> str:
        return f'From {self.name} <{self.email}>'

xray_genius/core/models/ct_input_file.py
from pathlib import Path

from django.db import models
from django.db.models import signals
from django.dispatch import receiver
from django_extensions.db.fields import CreationDateTimeField
from s3_file_field.fields import S3FileField

from .sample_dataset import SampleDatasetFile


class CTInputFile(models.Model):
    created = CreationDateTimeField()

    file = S3FileField()

    def __str__(self) -> str:
        return self.filename

    @property
    def filename(self):
        return Path(self.file.name).name


@receiver(signals.post_delete, sender=CTInputFile)
def delete_file(sender: type[CTInputFile], instance: CTInputFile, **kwargs):
    # Only delete the associated S3 blob if it is not part of a sample dataset
    if not SampleDatasetFile.objects.filter(file=instance.file).exists():
        instance.file.delete()

xray_genius/core/models/output_image.py
from django.db import models
from django.db.models import signals
from django.dispatch import receiver
from django_extensions.db.fields import CreationDateTimeField

from .session import Session


class OutputImage(models.Model):
    created = CreationDateTimeField()
    image = models.ImageField(upload_to='output_images')
    thumbnail = models.ImageField(upload_to='output_images/thumbnails')
    session = models.ForeignKey(Session, on_delete=models.CASCADE, related_name='output_images')

    # Parameters for this specific output image
    carm_push_pull = models.FloatField(null=True, blank=True)
    carm_head_foot_translation = models.FloatField(null=True, blank=True)
    carm_raise_lower = models.FloatField(null=True, blank=True)
    carm_alpha = models.FloatField(
        null=True, blank=True, help_text='The desired alpha angulation of the C-arm in degrees.'
    )
    carm_beta = models.FloatField(
        null=True, blank=True, help_text='The desired secondary angulation of the C-arm in degrees.'
    )

    def __str__(self) -> str:
        return f'Output Image {self.pk} (Session {self.session_id})'


@receiver(signals.pre_delete, sender=OutputImage)
def delete_file(sender: type[OutputImage], instance: OutputImage, **kwargs):
    instance.image.delete(save=False)
    instance.thumbnail.delete(save=False)

xray_genius/core/models/sample_dataset.py
from django.db import models


class SampleDataset(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    license = models.TextField()
    source_name = models.TextField()
    source_url = models.URLField()

    def __str__(self) -> str:
        return self.name


class SampleDatasetFile(models.Model):
    sample_dataset = models.ForeignKey(
        SampleDataset, on_delete=models.CASCADE, related_name='files'
    )

    name = models.CharField(max_length=255)
    description = models.TextField()
    file = models.FileField(upload_to='sample_data')

    def __str__(self) -> str:
        return self.name

xray_genius/core/models/session.py
from __future__ import annotations

import uuid

from django.contrib.auth.models import User
from django.db import models
from django.db.models.functions import Extract, Now
from django_extensions.db.fields import CreationDateTimeField

from .ct_input_file import CTInputFile


class SessionManager(models.Manager):
    def get_queryset(self) -> models.QuerySet[Session]:
        # Hide sessions that are being deleted
        return super().get_queryset().exclude(status=Session.Status.DELETING)


class StuckSessionsManager(models.Manager):
    def get_queryset(self) -> models.QuerySet[Session]:
        # Get sessions that have been running or queued for too long
        return (
            super()
            .get_queryset()
            .alias(
                seconds_running=Extract(Now(), 'epoch') - Extract(models.F('started'), 'epoch'),
                # Assume each generation takes 15 seconds at the most
                seconds_expected=models.F('parameters__num_samples') * 15,
            )
            .filter(
                status__in=[Session.Status.QUEUED, Session.Status.RUNNING],
                seconds_running__gt=models.F('seconds_expected'),
            )
        )


class Session(models.Model):
    class Status(models.TextChoices):
        NOT_STARTED = 'not-started', 'Not Started'
        QUEUED = 'queued', 'Queued'
        RUNNING = 'running', 'Running'
        PROCESSED = 'processed', 'Processed'
        CANCELLED = 'cancelled', 'Cancelling'
        DELETING = 'deleting', 'Deleting'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = CreationDateTimeField()
    started = models.DateTimeField(
        help_text='When the session started processing (i.e. when it went into the QUEUED state)',
        null=True,
        blank=True,
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sessions')
    input_scan = models.ForeignKey(CTInputFile, on_delete=models.CASCADE, related_name='sessions')
    status = models.CharField(max_length=32, choices=Status.choices, default=Status.NOT_STARTED)
    celery_task_id = models.CharField(max_length=255, default='')

    output_images_zip = models.FileField(upload_to='output_images/zips', null=True, blank=True)

    objects = SessionManager()
    stuck_objects = StuckSessionsManager()

    def __str__(self) -> str:
        return f'Session {self.id} ({self.status})'

xray_genius/core/forms.py
from captcha.fields import CaptchaField
from django.contrib.auth.models import User
from django.forms import ModelForm

from .models import ContactFormSubmission, CTInputFile


class CTInputFileUploadForm(ModelForm):
    class Meta:
        model = CTInputFile
        fields = ['file']


class ContactForm(ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = ContactFormSubmission
        fields = ['name', 'email', 'message']

    def __init__(self, *args, user: User, **kwargs):
        super().__init__(*args, **kwargs)

        # If the user is logged in, don't show the captcha
        if user.is_authenticated:
            del self.fields['captcha']

xray_genius/core/views.py
from collections.abc import Callable
from typing import ParamSpec, TypeVar
from urllib.parse import urlencode

from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied, SuspiciousOperation
from django.db import transaction
from django.db.models import Exists, OuterRef, Subquery
from django.http import Http404, HttpRequest, HttpResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect, render
from django.template import Context, Template
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.http import require_GET, require_http_methods, require_POST
from django_celery_results.models import TaskResult
from login_required import login_not_required

from .forms import ContactForm, CTInputFileUploadForm
from .models import CTInputFile, SampleDataset, SampleDatasetFile, Session
from .tasks import (
    delete_session_task,
    run_deepdrr_task,
    send_contact_form_submission_to_admins_task,
)

T = TypeVar('T')
P = ParamSpec('P')


def ws_url_prefix(request: HttpRequest) -> str:
    scheme = 'wss' if request.is_secure() else 'ws'
    return f'{scheme}://{request.get_host()}'


def user_has_reached_session_limit(user: User) -> bool:
    if user.is_superuser or user.is_staff:
        # Superusers and staff can start as many sessions as they want
        return False
    return Session.objects.filter(owner=user).count() >= settings.USER_SESSION_LIMIT


def quota_check[**P, T](view: Callable[P, T]) -> Callable[P, T]:
    def check(request: HttpRequest, *args, **kwargs):
        if user_has_reached_session_limit(request.user):
            raise SuspiciousOperation(
                'User has reached session limit, but tried to start a new session through the API.'
            )
        return view(request, *args, **kwargs)

    return check


def permission_check[**P, T](view: Callable[P, T]) -> Callable[P, T]:
    def check(request: HttpRequest, *args, **kwargs):
        if session_pk := kwargs.get('session_pk'):
            session = get_object_or_404(Session, pk=session_pk)
            if session.owner != request.user:
                raise Http404
        return view(request, *args, **kwargs)

    return check


@permission_check
@require_GET
def dashboard(request: HttpRequest):
    sessions = (
        Session.objects.select_related('input_scan', 'parameters')
        .prefetch_related('output_images')
        .filter(owner=request.user)
        .order_by('-created')
        .annotate(
            has_task_result=Subquery(
                Exists(
                    TaskResult.objects.filter(
                        task_id=OuterRef('celery_task_id'),
                    )
                ),
            ),
        )
    )

    # Whether or not the page should refresh every 5 seconds automatically.
    should_refresh = sessions.filter(
        status__in=(Session.Status.QUEUED, Session.Status.RUNNING)
    ).exists()

    return render(
        request,
        'dashboard.html',
        {
            'sessions': sessions,
            'SessionStatus': Session.Status,
            'should_refresh': should_refresh,
            'should_disable_new_session_button': user_has_reached_session_limit(request.user),
            'ws_url_prefix': ws_url_prefix(request),
        },
    )


@permission_check
@quota_check
@require_http_methods(['GET', 'POST'])
def upload_ct_input_file(request: HttpRequest):
    if request.method == 'POST':
        form = CTInputFileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            with transaction.atomic():
                file = form.save()
                session = Session.objects.create(owner=request.user, input_scan=file)
            # Redirect to VolView viewer with the uploaded file
            return redirect(
                reverse('viewer', kwargs={'session_pk': session.pk})
                + '?'
                + urlencode({'urls': file.file.url})
            )
    else:
        form = CTInputFileUploadForm()
    return render(
        request,
        'upload_ct_file.html',
        {
            'form': form,
            'sample_datasets': SampleDataset.objects.prefetch_related('files'),
        },
    )


@permission_check
@quota_check
@require_POST
def start_session_with_sample_data(request: HttpRequest, sample_dataset_file_pk: int):
    sample_dataset = get_object_or_404(SampleDatasetFile, pk=sample_dataset_file_pk)
    with transaction.atomic():
        ct_input_file = CTInputFile.objects.create(file=sample_dataset.file)
        session = Session.objects.create(owner=request.user, input_scan=ct_input_file)
        return redirect(
            reverse('viewer', kwargs={'session_pk': session.pk})
            + '?'
            + urlencode({'urls': ct_input_file.file.url})
        )


@permission_check
@require_POST
def delete_session(request: HttpRequest, session_pk: str):
    # Only staff and superusers can delete sessions
    if not request.user.is_staff and not request.user.is_superuser:
        raise SuspiciousOperation('Non-admin attempted to delete a session.')

    with transaction.atomic():
        session = get_object_or_404(Session.objects.select_for_update(), pk=session_pk)
        session.status = Session.Status.DELETING
        session.save()
    delete_session_task.delay(session_pk)
    return redirect('dashboard')


@permission_check
@require_GET
def download_ct_file(request: HttpRequest, session_pk: str):
    session = get_object_or_404(Session, pk=session_pk)
    return redirect(session.input_scan.file.url)


@permission_check
@require_GET
def volview_viewer(request: HttpRequest, session_pk: str):
    session = get_object_or_404(Session, pk=session_pk)
    return render(request, 'viewer.html', context={'session': session})


@permission_check
@require_POST
def initiate_batch_run(request: HttpRequest, session_pk: str):
    with transaction.atomic():
        session = get_object_or_404(Session.objects.select_for_update(), pk=session_pk)
        if not session.parameters:
            # Error: parameters missing. The UI should prevent this from ever happening.
            return HttpResponseBadRequest('Parameters missing')
        if session.status != Session.Status.NOT_STARTED:
            return HttpResponseBadRequest('Invalid start state.')
        session.status = Session.Status.QUEUED
        session.started = timezone.now()
        session.save()
    task = run_deepdrr_task.delay(session_pk)
    Session.objects.filter(pk=session_pk).update(celery_task_id=task.id)
    return redirect('dashboard')


@permission_check
@require_POST
def cancel_batch_run(request: HttpRequest, session_pk: str):
    with transaction.atomic():
        session = get_object_or_404(Session.objects.select_for_update(), pk=session_pk)
        session.status = Session.Status.CANCELLED
        session.started = None
        session.save()
    return redirect('dashboard')


@require_GET
def get_task_trace(request: HttpRequest, session_pk: str):
    # Only staff and superusers can view task info, regardless of
    # who owns the session.
    if not request.user.is_staff and not request.user.is_superuser:
        raise PermissionDenied
    session = get_object_or_404(Session, pk=session_pk)
    task_result = get_object_or_404(TaskResult, task_id=session.celery_task_id)
    return render(
        request,
        'task_trace.html',
        context={
            'task_result': task_result,
        },
    )


@login_not_required
@require_http_methods(['GET', 'POST'])
def contact_form(request: HttpRequest):
    user: User = request.user
    if request.method == 'POST':
        form = ContactForm(request.POST, user=user)
        if form.is_valid():
            form.save()
            send_contact_form_submission_to_admins_task.delay(form.instance.pk)
            return redirect('contact-submitted')
    else:
        form = ContactForm(user=user)

    return render(request, 'contact_form.html', {'form': form})


@login_not_required
@require_GET
def contact_form_submitted(request: HttpRequest):
    return render(request, 'contact_form_submitted.html')


@login_not_required
@require_GET
def terms_of_service(request: HttpRequest):
    return HttpResponse(
        content=Template(template_string=render_to_string('terms_of_service.html')).render(
            context=Context({'request': request})
        )
    )


@login_not_required
@require_GET
def guide(request: HttpRequest):
    return render(request, 'guide.html')


@login_not_required
@require_GET
def faq(request: HttpRequest):
    return render(request, 'faq.html')

xray_genius/core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html data-theme="dark">
  <head>
    {% include 'snippets/base_head.html' %}
  </head>
  <body>
    {% include 'snippets/sentry.html' %}

    {% include 'snippets/navbar.html' %}

    {% block body %} {% endblock body %}
  </body>
</html>

xray_genius/core/templates/contact_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block body %}
  <div class="flex justify-center items-center min-h-screen">
    <form
      method="post"
      action="{% url 'contact' %}"
      class="card w-full max-w-lg bg-base-200 shadow-xl p-6 sm:p-8"
    >
      {% csrf_token %}
      <h2 class="card-title text-center mb-6">Contact Us</h2>

      <div class="form-control mb-4">
        <label for="id_name" class="label">
          <span class="label-text">Your Name</span>
        </label>
        {% if form.name.errors %}
          <div class="text-md text-error mb-4">{{ form.name.errors|join:", " }}</div>
        {% endif %}
        {% render_field form.name class="input input-bordered w-full" placeholder="Enter your name" %}
      </div>

      <div class="form-control mb-4">
        <label for="id_email" class="label">
          <span class="label-text">Your Email</span>
        </label>
        {% if form.email.errors %}
          <div class="text-md text-error mb-4">{{ form.email.errors|join:", " }}</div>
        {% endif %}
        {% render_field form.email class="input input-bordered w-full" placeholder="Enter your email" %}
      </div>

      <div class="form-control mb-4">
        <label for="id_message" class="label">
          <span class="label-text">Your Message</span>
        </label>
        {% if form.message.errors %}
          <div class="text-md text-error mb-4">{{ form.message.errors|join:", " }}</div>
        {% endif %}
        {% render_field form.message class="textarea textarea-bordered w-full" placeholder="Write your message" rows="4" %}
      </div>

      {% if form.captcha %}
        <div class="form-control mb-4">
          <label for="id_captcha" class="label">
            <span class="label-text">Enter the characters in the image below:</span>
          </label>
          {% if form.captcha.errors %}
            <div class="text-md text-error mb-4">{{ form.captcha.errors|join:", " }}</div>
          {% endif %}
          {% render_field form.captcha class="m-4" %}
        </div>
      {% endif %}

      <div class="form-control mt-6">
        <button
          type="submit"
          class="btn btn-primary w-full"
        >
          Send Message
        </button>
      </div>
    </form>
  </div>
{% endblock body %}

xray_genius/core/templates/contact_form_submitted.html
{% extends "base.html" %}

{% block body %}
  <div class="flex justify-center items-center min-h-screen bg-base-100">
    <div class="card w-full max-w-lg bg-base-200 shadow-xl p-6 text-center">
      <h2 class="card-title text-success text-center mb-6">Thank You!</h2>
      <p class="mb-4 text-lg">
        Your message has been successfully sent. Thank you for using X-ray Genius!
      </p>
      <div class="form-control mt-6">
        <a href="/" class="btn btn-primary w-full">
          Return to Home
        </a>
      </div>
    </div>
  </div>
{% endblock body %}

xray_genius/core/templates/faq.html
{% extends "base.html" %}

{% load render_markdown_file %}

{% block body %}
  <div class="container mx-auto py-8">
    <div class="prose">
      {% autoescape off %}
        {{ "faq.md"|render_markdown_file }}
      {% endautoescape %}
    </div>
  </div>
{% endblock body %}

xray_genius/core/templates/guide.html
{% extends "base.html" %}

{% load render_markdown_file %}

{% block body %}
  <div class="container mx-auto py-8">
    <div class="prose">
      {% autoescape off %}
        {{ "guide.md"|render_markdown_file }}
      {% endautoescape %}
    </div>
  </div>
{% endblock body %}

xray_genius/core/templates/task_trace.html
{% extends 'base.html' %}
{% block body %}
  <div class="bg-neutral m-4 p-4 rounded-lg shadow-lg">
    <h2 class="text-xl font-semibold mb-2">Task Result Details</h2>
    <div class="grid grid-cols-2 gap-4">
      <div>
        <p class="font-semibold">Task ID:</p>
        <p>{{ task_result.task_id }}</p>
      </div>
      <div>
        <p class="font-semibold">Task Name:</p>
        <p>{{ task_result.task_name }}</p>
      </div>
      <div>
        <p class="font-semibold">Task State:</p>
        <p>{{ task_result.get_status_display }}</p>
      </div>
      <div>
        <p class="font-semibold">Worker:</p>
        <p>{{ task_result.worker }}</p>
      </div>
      <div>
        <p class="font-semibold">Started at:</p>
        <p>{{ task_result.date_created }}</p>
      </div>
      <div>
        <p class="font-semibold">Completed at:</p>
        <p>{{ task_result.date_done }}</p>
      </div>
      <div class="col-span-2">
        <p class="font-semibold">Traceback (scrollable):</p>
        <pre class="text-sm overflow-auto max-h-40">
          {{ task_result.traceback|default:"No traceback available" }}
        </pre>
      </div>
    </div>
  </div>

{% endblock body %}

xray_genius/core/templates/terms_of_service.html
{% extends "base.html" %}

{% load render_markdown_file %}

{% block body %}
  <div class="m-4">
    <a href="{% url 'account_signup' %}">
      <button class="btn btn-md btn-primary">
        <i class="ri-arrow-go-back-fill"></i> Back to Sign Up
      </button>
    </a>
  </div>
  <div class="container mx-auto py-8">
    <div style="all: initial;">
      <div class="prose">
        {% autoescape off %}
          {{ "terms_of_service.md"|render_markdown_file }}
        {% endautoescape %}
      </div>
    </div>
  </div>
{% endblock body %}

xray_genius/core/templates/upload_ct_file.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% block body %}
  <head>
    {{ form.media }}
  </head>
  <div class="bg-gray-900 border border-gray-700 p-8 m-4 rounded-lg text-center">
    <h2 class="text-xl font-bold text-white mb-4">Choose a Sample Dataset</h2>

    <div>
      <label for="sampleDataModal" class="btn btn-primary">
        Choose Sample Data
      </label>
    </div>

    <input type="checkbox" id="sampleDataModal" class="modal-toggle" />
    <div class="modal">
      <div class="modal-box bg-gray-900 text-white relative max-w-4xl">
        <label
          for="sampleDataModal"
          class="btn btn-sm btn-circle absolute right-2 top-2"
          aria-label="Close"
        >✕</label
          >

          <h2 class="text-2xl font-bold mb-4">Available Sample Datasets</h2>

          <div class="space-y-4">
            {% for dataset in sample_datasets %}
              <div class="collapse bg-gray-800 border border-gray-700 rounded-lg">
                <input type="checkbox" class="peer" />
                <div
                  class="collapse-title flex justify-between items-center p-4 text-lg font-semibold text-gray-200"
                >
                  {{ dataset.name }}
                  <i class="ri-arrow-drop-down-line text-4xl"></i>
                </div>
                <div class="collapse-content p-4 text-left">
                  <div class="mt-2 text-sm text-gray-300 flex flex-wrap gap-2">
                    <span class="badge badge-primary whitespace-normal">
                      <strong>License:&nbsp;</strong> {{ dataset.license }}
                    </span>
                    <span class="badge badge-info whitespace-normal">
                      <strong>Source:&nbsp;</strong>
                      {{ dataset.source_name }}&nbsp;
                      <a class="link" href="{{ dataset.source_url }}">(link)</a>
                    </span>
                  </div>

                  <p class="mt-4 text-sm text-gray-400">{{ dataset.description }}</p>

                  <div class="overflow-x-auto mt-4">
                    <table class="table-auto w-full text-left text-white">
                      <thead>
                        <tr class="bg-gray-800">
                          <th class="px-4 py-2">File Name</th>
                          <th class="px-4 py-2">Description</th>
                          <th class="px-4 py-2">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for file in dataset.files.all %}
                          <tr class="border-t border-gray-700">
                            <td class="px-4 py-2">{{ file.name }}</td>
                            <td class="px-4 py-2">{{ file.description }}</td>
                            <td class="px-4 py-2">
                              <form
                                method="post"
                                action="{% url 'create-session-from-sample-data' file.id %}"
                              >
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary btn-sm">
                                  Start Session with this File
                                </button>
                              </form>
                            </td>
                          </tr>
                        {% empty %}
                          <tr>
                            <td colspan="3" class="px-4 py-2 text-gray-500">
                              No files available.
                            </td>
                          </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            {% empty %}
              <p class="text-gray-500">No datasets available.</p>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>

    {% if request.user.is_superuser or request.user.is_staff %}
      <div
        class="bg-gray-800 border-dashed border-4 border-neutral p-8 m-4 rounded-lg text-center"
      >
        <h2 class="text-xl font-bold text-white mb-4">Or Upload Your Own Files (Admins Only)</h2>

        <form
          method="post"
          enctype="multipart/form-data"
          action="{% url 'create-session' %}"
        >
          {% csrf_token %}
          <div class="mb-4">
            <label for="fileInput" class="btn btn-accent">
              Choose Files to Upload
            </label>
            {% render_field form.file id="fileInput" class="hidden" %}
          </div>

          {% if form.errors %}
            <div class="alert alert-error mt-4">
              <i class="ri-error-warning-fill"></i>
              <div>{{ form.errors }}</div>
            </div>
          {% endif %}
          <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded mt-4">
            Start session with uploaded file
          </button>
        </div>
    {% endif %}
  </form>

{% endblock %}

xray_genius/core/templates/viewer.html
{% load django_vite %}
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {# Needed by Vuetify #}
    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@7.x/css/materialdesignicons.min.css" rel="stylesheet">

    <title>X-ray Genius</title>

    {% vite_hmr_client %}
    {% vite_asset 'src/main.js' %}
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>